language: cpp
jobs:
  include:
   - os: linux
     dist: bionic
     compiler: gcc
     script : cmake . && make && echo wait 10 > run_test.txt && echo exit >> run_test.txt && cat run_test.txt | ./UxVCtrl 

   - os: linux
     dist: bionic
     compiler: gcc
     script : cmake -DDISABLE_OPENCV_SUPPORT=OFF -DOPENCV2413=OFF -DOPENCV320=ON -DENABLE_MAVLINK_SUPPORT=ON -DENABLE_SBG_SUPPORT=ON -DENABLE_LABJACK_SUPPORT=ON -DENABLE_LIBMODBUS_SUPPORT=ON -DENABLE_BLUEVIEW_SUPPORT=ON . && make && echo wait 10 > run_test.txt && echo exit >> run_test.txt && cat run_test.txt | ./UxVCtrl 
 
   - os: linux
     dist: xenial
     compiler: gcc
     script : cmake . && make && echo wait 10 > run_test.txt && echo exit >> run_test.txt && cat run_test.txt | ./UxVCtrl 
 
   - os: linux
     dist: trusty
     compiler: gcc
     script : cmake . && make && echo wait 10 > run_test.txt && echo exit >> run_test.txt && cat run_test.txt | ./UxVCtrl 
 
   - os: linux
     dist: precise
     compiler: gcc
     script : cmake . && make && echo wait 10 > run_test.txt && echo exit >> run_test.txt && cat run_test.txt | ./UxVCtrl 
 
   - os: osx
     script : cmake . && make && echo wait 10 > run_test.txt && echo exit >> run_test.txt && cat run_test.txt | ./UxVCtrl 

   - os: windows
     install: PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'
     script : cmd /c 'cmake -G "Visual Studio 15" . & msbuild UxVCtrl.vcxproj /m /t:Rebuild /p:Configuration=Debug & @echo wait 10 > run_test.txt & @echo exit >> run_test.txt & .\Debug\UxVCtrl.exe < run_test.txt & msbuild UxVCtrl.vcxproj /m /t:Rebuild /p:Configuration=Release & @echo wait 10 > run_test.txt & @echo exit >> run_test.txt & .\Release\UxVCtrl.exe < run_test.txt'

   - os: windows
     install: PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'
     script : cmd /c 'cmake -G "Visual Studio 15" -DDISABLE_OPENCV_SUPPORT=OFF -DOPENCV2413=OFF -DOPENCV410=ON -DENABLE_MAVLINK_SUPPORT=ON -DENABLE_SBG_SUPPORT=ON -DENABLE_LIBMODBUS_SUPPORT=ON -DENABLE_BLUEVIEW_SUPPORT=ON . & msbuild UxVCtrl.vcxproj /m /t:Rebuild /p:Configuration=Debug & @echo wait 10 > run_test.txt & @echo exit >> run_test.txt & .\Debug\UxVCtrl.exe < run_test.txt & msbuild UxVCtrl.vcxproj /m /t:Rebuild /p:Configuration=Release & @echo wait 10 > run_test.txt & @echo exit >> run_test.txt & .\Release\UxVCtrl.exe < run_test.txt'
